blank_issues_enabled: false
contact_links:
  - name: Tacktion Engine Support
    url: https://forum.juce.com/c/tracktion-engine/27
    about: Please use the JUCE forum to ask questions with the tracktion_engine category.
  - name: Bugs and FRs
    url: https://github.com/Tracktion/tracktion_engine/issues
    about: Please submit bugs and feature requests as GitHub issues, folloing the appropriate template.
